- src/context/SocketContext.tsx
add `REACT_APP_WEBSOCKET_SERVER=https://clicker-api.ops.bitcoin.com/` environment variable
> add websocket server env var

- src/components/Bonuses/Burn.tsx
- src/contracts/verseEthereum.ts
- src/contracts/verseGoerli.ts
- src/contracts/versePolygon.ts
- src/helpers/getTokenDetails.ts
- src/hooks/useVerseBalance.ts
- tsconfig.json
shows verse balance based on chain in burns modal (will create separate pr to trigger burn... will need to do same with backend to detect and give user bonus)
> [MTDB-11000] Feature/different chains

- src/components/Boosts/Boosts.tsx
- src/components/Boosts/Hold.tsx
- src/components/Boosts/styled.ts
- src/components/Chip.ts
- src/components/LinkButton.ts
- update modal design
- show modal only when hold is locked (user doesn't hold verse)
> [MTDB-11311] Update hold modal design

- src/components/Boosts/Boosts.tsx
- src/components/Boosts/Hold.tsx
- able to open the modal even if the boost is unlocked
- set burn's boost to always be unlocked
> [MTDB-11311] Fix locked/unlocked logic on modal

- src/components/Marquee.tsx
- src/components/Modal/Modal.tsx
- src/components/Shop/ShopList/BuildingButton/BuildingButton.tsx
- src/components/Shop/ShopList/ShopList.tsx
- src/components/Shop/ShopList/styled.ts
- src/components/Shop/UpgradesList/UpgradesList.tsx
- src/components/WelcomeModal.tsx
- src/hooks/useIsOverflow.ts
- fixing scroll
- some tweaks wish shops list
- marquees on shops
> [MTDB-11314] Fix/random tweaks

- src/components/Boosts/Modals/Hold.tsx
- src/components/LinkButton.ts
> [MTDB-11476] Add buy more button on hold modal

- src/components/GameBoard/Cookie/Cookie.tsx
- src/components/Layout/Layout.tsx
- src/components/Shop/ShopList/BuildingButton/BuildingButton.tsx
- src/components/Shop/UpgradesList/UpgradeButton/UpgradeButton.tsx
- src/context/AudioProvider.tsx
> [MTDB-11473] Feature/audio context

- src/components/Loading/Loading.tsx
As per Pankaj's [update](https://www.figma.com/file/WY4ePoLTjDOomhsknBs37Z?node-id=323:8333&mode=design#599346563)
> Capitalize title

- src/components/Button.ts
- src/components/H3.ts
- src/components/Sidebar/Settings/ConfirmModal.tsx
- src/components/Sidebar/Settings/Settings.tsx
- src/components/Sidebar/Settings/styled.ts
- make confirm modal
- resets score of user to 0
[Figma](https://www.figma.com/file/WY4ePoLTjDOomhsknBs37Z/Verse-Clicker?type=design&node-id=340-23488&mode=design&t=k2YbUDQ9KfrcLfsU-0)
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/14491a52-b8d9-421f-87d8-0d58b8415bc9
> [MTDB-11010] Reset score functionality

- src/components/Boosts/Boosts.tsx
- src/components/Boosts/Modals/Farm.tsx
- src/components/Boosts/styled.ts
> [MTDB-11624] Fix/boosts

- src/components/Sidebar/Sidebar.tsx
- src/components/WelcomeModal/Content.tsx
- src/components/WelcomeModal/NewUser.tsx
- src/components/WelcomeModal/WelcomeModal.tsx
still need to finalize instructions and probably refine styling, but here's a start lol
> [MTDB-11629] Fix/info button

- src/components/Boosts/Modals/Burn/Burn.tsx
- src/components/Boosts/styled.ts
- src/components/Loading/Loading.tsx
- src/components/WelcomeModal/NewUser.tsx
- src/helpers/getExplorerLink.ts
> [MTDB-11626] fix verse points copy

- src/components/GameBoard/Cookie/Cookie.tsx
just jiggled some things arount to make auto click detection work
> [MTDB-11635] fix cheat prevention

- .env.development
- .env.localhost
- .env.production
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- src/components/Advertisement.tsx
looool I was using clicker as base url :(
> [MTDB-11017] Fix ad links

- src/components/GameBoard/Stats/styled.ts
- src/components/Header/styled.ts
- src/components/WelcomeModal/ReturningUser.tsx
- src/components/WelcomeModal/styled.ts
- src/context/RootProvider.tsx
**Fixes for:**
- Header width
- Long numbers breaking out of GameBoard
- Welcome Back modal icon colors
- Faded web3modal
> [MTDB-11627] Fix/misc style fixes

- src/components/WelcomeModal/WelcomeModal.tsx
- to avoid showing the modal with undefined data
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/8881bf58-3c19-4d7a-8e29-0337c327bbdb
> [MTDB-11628] Only show welcome back modal after 5 seconds

- src/components/GameBoard/Stats/Stats.tsx
- src/components/Sidebar/Leaderboard/Leaderboard.tsx
- src/components/Sidebar/Leaderboard/Row.tsx
- src/context/reducer.ts
- src/context/reducers/leaderboard.ts
- src/context/store.ts
- src/hooks/useSocketEvents.ts
- src/hooks/useUsername.ts
> [MTDB-11642] Feature/ens leaderboard

- src/components/Boosts/Modals/Burn/Burn.tsx
> disable burn button

- src/components/Advertisement.tsx
- src/components/Loading/Loading.tsx
- hide learn more link
- make adverts not open new tab if origin = wallet
> [MTDB-11620] Fix/wallet links

- src/context/RootProvider.tsx
setting prod/dev chains because i accidentally burned real verse
> setup diff chains for diff environments

- package.json
- yarn.lock
no ticket, just making github happy
> fix security vulnerabilities

- src/components/Sidebar/styled.ts
give sidebar a little background to make it stand out and match the boost buttons
> style sidebar like boost buttons

- src/buildings/polygon.json
- src/components/Sidebar/Leaderboard/styled.ts
- updated polygon names
- added margin-top on leaderboard list
> [MTDB-11940] Update polygon names and fix leaderboard styling

- src/components/Boosts/Modals/Burn/Burn.tsx
- src/components/Boosts/Modals/Burn/LoadingStates.tsx
- src/components/Boosts/styled.ts
- src/components/Icons/External.tsx
- src/components/Link.ts
- src/components/WelcomeModal/BurnBonus.tsx
- src/components/WelcomeModal/Content.tsx
- src/components/WelcomeModal/ReturningUser.tsx
- src/components/WelcomeModal/WelcomeModal.tsx
- src/components/WelcomeModal/styled.ts
- src/context/reducers/returnData.ts
> [MTDB-11630] Feature/reenable burn

- src/components/WelcomeModal/BonusList.tsx
- src/components/WelcomeModal/ReturningUser.tsx
- src/context/reducers/returnData.ts
- add scratcher bonus on welcome modal when user has claimed a prize
> [MTDB-11996] Scratcher bonus on welcome modal

- src/components/NotificationModal/BonusContent.tsx
- src/helpers/getExplorerLink.ts
- use "View on Polyscan" for polygon
- fix polygon tx link
> [MTDB-11996] Fix bonus link

- src/components/NotificationModal/Content.tsx
- src/components/Sidebar/Sidebar.tsx
> [MTDB-12135] Fix sidebar info modal content

- src/hooks/useCampaignInfo.ts
goddamn forward slashes
N/A
N/A
PR#
> fix campaign api url

- src/components/Loading/Loading.tsx
- src/components/Modal/Modal.tsx
- fix modal close not removing overflow hidden from body
N/A
N/A
PR#
> [MTDB-12295] Fix/modal close scroll

- package.json
- yarn.lock
> update wagmi to remove ledger

- src/components/Compaigns/Christmas/Before.tsx
- src/components/Compaigns/Christmas/Christmas.tsx
- src/components/Compaigns/Christmas/During.tsx
- src/hooks/useCampaignInfo.ts
> [MTDB-12291] Feature/campaign dates

- src/components/Compaigns/Christmas/Before.tsx
- src/components/Compaigns/Christmas/During.tsx
> [MTDB-12292] Fix clickmas modal titles copy

- src/components/Particles/config.ts
- src/components/themes/Christmas.ts
- src/views/NotConnected.tsx
- snow on not connected.
- tweak polygon particles
N/A
N/A
PR#
> [MTDB-12288] Fix/make it snow

- src/components/Compaigns/Christmas/Before.tsx
- src/components/Compaigns/Christmas/During.tsx
> [MTDB-12286] Add learn more link for clickmas

- src/buildings/christmas.json
> 12 clicks of clickmas

- src/components/Sidebar/Settings/Settings.tsx
> [MTDB-12290] fix reset game

- src/components/Boosts/Modals/Scratcher.tsx
- src/components/WarningChip.tsx
> [MTDB-12297] Feature/scratcher copy

- src/helpers/formatNumber.ts
this kinda makes more sense lol
> [MTDB-12294] Fix number formatter

- src/components/Compaigns/Christmas/Before.tsx
- src/components/Compaigns/Christmas/During.tsx
> [MTDB-12330] Open learn more link in a new tab

- src/components/Compaigns/Christmas/FinalLeaderboard.tsx
> [MTDB-12331] Fix leaderboard api url

- src/components/Banners/ClickmasBanner.tsx
- src/components/Banners/styled.ts
- src/components/Icons/Cross.tsx
- src/components/Layout/Layout.tsx
- src/context/reducer.ts
- src/context/reducers/campaign.ts
- src/context/store.ts
- show clickmas banner before and during the game 
> [MTDB-12324] Clickmas banner

- src/components/Layout/Layout.tsx
- forgot to add default value..
> [MTDB-12324] Set default value of `showCampaignBanner` to true

- src/components/Compaigns/Christmas/During.tsx
- change button color to secondary
- change copy to _Back to {chain}_
- put the button below learn more link
> [MTDB-12322] Return to base game button design fixes

- src/components/Banners/ClickmasBanner.tsx
> Fix clickmas banner link

- package.json
- yarn.lock
revert to *hopefully* be able to change chains
> [MTDB-12348] Revert wagmi version

- package.json
- yarn.lock
> re-update wagmi/web3modal

- src/components/Campaigns/Content/lunarnewyear.json
> [MTDB-12465] Update Lunar New Year modals content

- .eslintrc.json
- package.json
- src/components/Banners/Banner.tsx
- src/components/Campaigns/Campaign.tsx
- src/components/Campaigns/During.tsx
- src/components/Layout/Layout.tsx
- src/constants.ts
- src/context/SocketContext.tsx
- add `CURRENT_CAMPAIGN` in constants to not set the string one by one
- fixes "return to chain" button not showing
> Set current campaign to constants

- src/components/Boosts/Boosts.tsx
- src/components/Boosts/Modals/Hold.tsx
- src/components/Boosts/Modals/ScratcherLunar.tsx
- src/components/Boosts/Modals/ScratcherMint.tsx
- src/components/Boosts/styled.ts
- src/components/Campaigns/Campaign.tsx
- src/components/Icons/Lock.tsx
- src/components/NotificationModal/BonusContent.tsx
- src/components/NotificationModal/BonusList.tsx
- src/components/NotificationModal/ReturningUser.tsx
- src/context/reducers/bonusData.ts
- src/context/reducers/player.ts
- src/context/reducers/returnData.ts
- src/context/store.ts
Lunar new year bonuses
- Update store and reducers with new data models
- Add/Update bonuses modals for lunar new year
- Update bonus and return modals
N/A
PR#
> [MTDB-12468] Feature/lunar bonuses

- src/components/Banners/banner.json
- src/components/Campaigns/Before.tsx
- src/components/Campaigns/Content/christmas.json
- src/components/Campaigns/Content/lunarnewyear.json
- src/components/Campaigns/During.tsx
- src/components/Campaigns/types.ts
- src/components/NotificationModal/BonusContent.tsx
- add support link in `learn more` button
- change campaign title from _Lunaclick_ to _Verse Clicker Lunar New Year Contest_
- update prize amount to `$888`
> [MTDB-12582] Finalize Lunar New Year campaign copy

- src/components/Shop/ShopList/BuildingButton/BuildingButton.tsx
- src/components/Shop/ShopList/ShopList.tsx
- src/context/reducers/player.ts
- src/context/store.ts
> [MTDB-12626] Feature/unlocked buildings bonus

- src/context/SocketContext.tsx
reset game mode to chainname instead of game mode on disconnect
N/A
N/A
PR#
> [MTDB-12672] Feature/campaign-loading

- src/components/Campaigns/After.tsx
- src/components/Campaigns/Content/christmas.json
- src/components/Campaigns/Content/lunarnewyear.json
- src/components/Campaigns/FinalLeaderboard.tsx
- src/components/Campaigns/types.ts
> [MTDB-12682] Fix/campaign leaderboard

- src/components/NotificationModal/BonusList.tsx
> [MTDB-12677] fix bonus % display

- package.json
- yarn.lock
> add follow-redirects to resolutions to pass yarn audit

- src/components/Boosts/Modals/Scratcher.tsx
- src/components/Boosts/Modals/ScratcherLunar.tsx
- src/components/Boosts/Modals/ScratcherMint.tsx
> [MTDB-12674] Update to lunar new year support link

- src/components/GameBoard/Cookie/Cookie.tsx
reduce autoclick detection to 29, cause 30 doesnt seem to trigger reliably
N/A
N/A
PR#
> [MTDB-12673] Auto click detection

- src/context/RootProvider.tsx
workaround to let wc connect to polygon on bcom app
[slack thread here
](https://bitcoincom.slack.com/archives/C060DDRV022/p1706073118207739)
N/A
N/A
PR#
> workaround to enable polygon wc on bcom app

- public/sitemap.xml
> fix sitemap

- src/components/Boosts/Modals/ScratcherLunar.tsx
- src/components/Boosts/Modals/ScratcherMint.tsx
> [MTDB-12774] Capitalize word Scratcher

- src/components/GameBoard/Cookie/Cookie.tsx
- make it a whole number first before formatting the points per click
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/1faaaf26-7ee4-41b6-a2ae-c51cd4e2ff77
> [MTDB-12777] Fix NaN when clicking moon

- src/components/Campaigns/styled.ts
- make it glow to be visibleee
Uploading Screen Recording 2024-01-26 at 8.54.51.mov…
> [MTDB-12776] Make campaign button glow

- src/components/Campaigns/Campaign.tsx
- src/components/Campaigns/styled.ts
> [MTDB-12776] Fix button glow on mobile

- src/components/Boosts/Modals/Burn/Burn.tsx
- src/helpers/links.ts
Replaces with link to burn engine
> [MTDB-12813] - fix(burn): :recycle: Removes burn functionality

- src/components/Boosts/Modals/Burn/Burn.tsx
> [MTDB-12813] - fix(burn): :fire: Removes unused hooks

- src/components/GameBoard/Cookie/Cookie.tsx
- src/helpers/formatNumber.ts
- previous changes apparently didn't work :(( 
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/5d375ca2-79ff-480e-894a-b22ce395b45d
> Make click per second a whole number

- src/components/Banners/banner.json
- src/components/Boosts/Modals/Lounge.tsx
- src/components/Boosts/Modals/Scratcher.tsx
- src/components/Boosts/Modals/ScratcherLunar.tsx
- src/components/Boosts/Modals/ScratcherMint.tsx
- src/components/Campaigns/Content/lunarnewyear.json
- remove unused import
- update lunar new year support link
> LNY tweaks

- src/context/store.ts
> [MTDB-12773] Fix/campaign mode

- src/context/RootProvider.tsx
> update nodes for ethereum

- src/App.tsx
- src/components/Campaigns/Campaign.tsx
- src/context/SocketContext.tsx
- src/context/reducers/reset.ts
- src/context/store.ts
- src/helpers/gameMode.ts
> [MTDB-12773] Fix/multiple sessions

- src/components/Banners/Banner.tsx
- src/components/Layout/Layout.tsx
- src/context/reducers/campaign.ts
- src/context/reducers/settings.ts
- src/context/store.ts
- to permanently close it if the user closes it
> [MTDB-12838] Add campaignBanner in local storage

- src/components/NotificationModal/BonusContent.tsx
> fix bonus percentage display

- src/components/NotificationModal/BonusList.tsx
> fix return mint pc display

- src/components/GameBoard/Stats/Stats.tsx
> Fix NaN clicks when you reach 1k clicks

- .env.sample
- src/components/Modal/styled.ts
- src/helpers/liteMode.ts
- src/react-app-env.d.ts
Adds REACT_APP_LITE_MODE env config that hides backdrop-filter (for now) to reduce GPU usage on slower computers.
> perf(liteMode): :zap: Add lite mode option. Hide styles if true

- public/404.html
Removing 404 so cloudflare pages recognises build as a singe-page application...
https://developers.cloudflare.com/pages/configuration/serving-pages/#single-page-application-spa-rendering
N/A
N/A
PR#
> remove 404 so cloudflare recognises as spa

- src/components/Loading/Loading.tsx
> some sign copy and cleanup

- src/components/Loading/Loading.tsx
> revert sig back to state

- src/components/Loading/Loading.tsx
- src/context/reducer.ts
- src/context/reducers/sign.ts
> verify sign on client to fix broken states

- package.json
- yarn.lock
> update packages for security warnings

- src/components/Header/Header.tsx
- src/components/Header/styled.ts
- src/components/Sidebar/Leaderboard/Leaderboard.tsx
- src/views/Leaderboard.tsx
> [MTDB-13948] - refactor(header/leaderboard): :recycle: Fix back navigation and leaderboards native navigation

- src/components/Leaderboard/styled.ts
> style(leaderboard): :lipstick: Fix spacing for desktop (columns of header are looking a bit off)

- README.md
> smol change

- src/components/Header/Connect/GameModesList.tsx
> [MTDB-14091] Fix/Game mode switch

- src/App.tsx
- src/components/Header/Header.tsx
- handles navigation if history is cleared
- back on home goes to dex
- reload leaderboards doesn't append campaign
N/A
N/A
PR#
> [MTDB-14177] Fix/history navigation

- src/components/Header/ConnectButton.tsx
> disable button if connecting

- .github/CODEOWNERS
> [MTDB-15295]add codeowners file
