bitcoin-verse/verse-clicker

src/components/Advertisement.tsx
src/components/GameBoard/GameBoard.tsx
src/components/Shop/ShopList/ShopList.tsx

- position under buildings/upgrades on bigger screen
- position under boosts on smaller screen
- add radius to ad image

[MTDB-11460] Fix positioning of Advertisement section

---

src/components/Boosts/Boosts.tsx
src/components/Boosts/Modals/Farm.tsx
src/context/reducers/player.ts
src/context/store.ts

- dev designed since there's no design for this, just reused hold modal's content
- add `isFarming` and `isStaking` to `Player` object
- use `isFarming` and `isStaking` to display diff content on modal
**Doesn't have farms or staking**
**Has farms or staking**

[MTDB-11475] Update farm modal design

---

src/components/Boosts/Boosts.tsx
src/components/Boosts/styled.ts

[MTDB-11311] Remove unlock text and display boosts in one line

---

src/components/GameBoard/Stats/Stats.tsx
src/components/Icons/Cursor.tsx
src/components/Sidebar/Leaderboard/Leaderboard.tsx
src/components/Sidebar/Leaderboard/styled.ts

- limit leaderboard list to 10
- add cursor instead of verse icon to clicks
- use monospace font for numbers
- add user at bottom of leaderboard if not top 10

[MTDB-11622] Feature/leaderboard

---

src/components/WelcomeModal/NewUser.tsx
src/components/WelcomeModal/styled.ts

i went with option #3 but took some liberties lol
> like this option the best but with some tweaks:
> - should say Verse Clicker logo as it’s not exactly the verse logo
> - switching order of Tools and Upgrades and capitalize maybe(??) since that’s the order they’re displayed in
> - use the word boost instead of supercharge since that’s what is used in the boost section

[MTDB-11629] tweak instructions and styles in welcome modal

---

src/components/GameBoard/Stats/Stats.tsx
src/components/Sidebar/Leaderboard/Leaderboard.tsx
src/components/Sidebar/Leaderboard/styled.ts
src/components/Sidebar/styled.ts

- show top 25 (websocket already returns this)
- add scrolling as to not make modal to biiiig
- make sidebar buttons larger so they stand out more on desktop

increase leaderboard size and add scrolling

---

src/components/Sidebar/Leaderboard/styled.ts

only right pad leaderboard if desktop

fix leaderboard scroll/padding on mobile

---

src/components/GameBoard/PointsDisplay/styled.ts
src/components/Sidebar/Leaderboard/styled.ts

when using safari mobile, svg is flickering 
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/969984d9-5386-440b-b84a-2df4718aecaf

[MTDB-12133] Fix flickering svg on leaderboards

---

src/context/SocketContext.tsx
src/context/store.ts

- makes `campaign=xxx` query case insensitive
- reset game and game mode on disconnect (handles when campaign is inactive)
N/A
N/A
PR#

[MTDB-12256] Fix/campaign query

---

src/context/SocketContext.tsx

- add `campaign=Christmas` in url when starting clickmas
- remove `campaign` query when switching back to chains
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/b1bf49fa-bd24-4f80-a8cb-60b98958f7e5

[MTDB-12332] Fix game reconnection

---

src/components/NotificationModal/ReturningUser.tsx

add label to return modal to inform users of max offline point production
N/A
PR#

add label to return modal to inform max point production

---

src/components/Boosts/Boosts.tsx
src/components/Boosts/Modals/Lounge.tsx
src/constants.ts

- add lounge boost for guild members
- this boost is only enabled during lunar new year

[MTDB-12662] Add lounge boost only for lunar new year campaign

---

src/components/GameBoard/Cookie/Cookie.tsx
src/components/GameBoard/Stats/Stats.tsx

- make it a whole number
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/3d0a9a4e-ce54-486e-9535-1aab4d2eed56

[MTDB-12670] Remove decimal on clicks and stats

---

src/components/Header/ConnectButton.tsx

This is a crappy workaround for network not getting updated on reject connection due to this bug https://github.com/WalletConnect/web3modal/issues/1546
N/A
N/A
PR#

[MTDB-12680] reload page on wc "CONNECT_ERROR"

---

src/components/NotificationModal/BonusList.tsx

looks like this was the only date localization that specified `en-US`
N/A
N/A
PR#

[MTDB-12675] remove locale arg from date localization

---

src/components/Banners/styled.ts

[MTDB-12671] Fix overlapping banner on mobile

---

src/components/Boosts/Modals/Lounge.tsx

[MTDB-12836] Remove Get Verse button in lounge modal

---

src/components/Campaigns/Before.tsx
src/components/Campaigns/During.tsx

- display so users wont get confused

[MTDB-12909] Display user local's offset on campaign modal dates

---

src/components/Shop/ShopList/BuildingButton/BuildingButton.tsx

- add `purchaseAmount` as a dependency in `useMemo` so the tools amount & cost change when the multiplier changes
https://github.com/bitcoin-verse/verse-clicker/assets/94164690/65704a59-17f9-418d-8937-c50f2f531a4c

[MTDB-12871] Fix tools amount & cost when changing multiplier

---

src/components/Layout/Layout.tsx

- there was a weird "learn more" banner that's not clickable lol

Remove banner when there's no current campaign
